// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGWykXGS7B7maNi01PmtH6v66tvOhwnBE',
    appId: '1:79411404755:web:25c0861a5e066e35449926',
    messagingSenderId: '79411404755',
    projectId: 'one-tap-ap',
    authDomain: 'one-tap-ap.firebaseapp.com',
    storageBucket: 'one-tap-ap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK8goK3X7jd9rG6hxggBiDmQ-Wk9t8I1A',
    appId: '1:79411404755:android:bd1d7f3dc1a188e4449926',
    messagingSenderId: '79411404755',
    projectId: 'one-tap-ap',
    storageBucket: 'one-tap-ap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9lDxOzy4sbx_Ybxi4rxaOELxeQEJfr7Y',
    appId: '1:79411404755:ios:6323c81c97bdf6dc449926',
    messagingSenderId: '79411404755',
    projectId: 'one-tap-ap',
    storageBucket: 'one-tap-ap.firebasestorage.app',
    iosBundleId: 'com.example.oneTap',
  );
}
